import { Check, ChevronRight, Plane, Search, ShoppingBag, Star } from "lucide-react";
import type { PageKind, ResultKind } from "@/types/pilot";

export const elementRows = [
  { index: 3, type: "button", label: "Flights" }, { index: 5, type: "textbox", label: "Search" },
  { index: 8, type: "textbox", label: "Find food" }, { index: 11, type: "link", label: "Product results" },
  { index: 12, type: "link", label: "Piccolo Forno" }, { index: 14, type: "textbox", label: "Where to?", value: "Dubai" },
  { index: 17, type: "combobox", label: "Sort products" }, { index: 18, type: "button", label: "Travel dates" },
  { index: 19, type: "button", label: "Margherita" }, { index: 24, type: "button", label: "Review basket" },
  { index: 26, type: "link", label: "Review summary" }, { index: 27, type: "button", label: "Compare fares" },
  { index: 29, type: "button", label: "Place order" }, { index: 31, type: "button", label: "Emirates nonstop" },
  { index: 33, type: "button", label: "Save shortlist" },
] as const;

const IndexBadge = ({ n }: { n: number }) => <span className="element-index">#{n}</span>;

function FlightsPage() {
  return <div className="mock-page bg-page"><div className="mock-nav"><b className="text-page-strong">Aero</b><span>Explore</span><span className="text-page-strong">Flights</span><span>Hotels</span></div><div className="mx-auto max-w-3xl px-8 py-10"><p className="text-sm font-medium text-page-muted">Round trip · 1 passenger · Economy</p><h2 className="mt-2 text-3xl font-semibold text-page-strong">Where do you want to go?</h2><div className="mt-7 grid grid-cols-[1fr_auto_1fr] items-center gap-2 rounded-2xl border border-page-border bg-page-card p-3 shadow-xl"><div className="relative rounded-xl border border-page-border p-3"><span className="text-xs text-page-muted">From</span><p className="font-semibold text-page-strong">New York · JFK</p></div><Plane className="size-4 text-page-muted"/><div className="relative rounded-xl border-2 border-agent p-3"><IndexBadge n={14}/><span className="text-xs text-page-muted">To</span><p className="font-semibold text-page-strong">Dubai · DXB</p></div></div><div className="mt-6 flex items-center justify-between"><div><p className="font-semibold text-page-strong">Best departing flights</p><p className="text-sm text-page-muted">Sorted by price and convenience</p></div><span className="rounded-full bg-page-soft px-3 py-1 text-xs text-page-muted">3 results</span></div><div className="mt-4 space-y-3">{[["Emirates","8:10 PM","6:45 PM","Nonstop","$842",31],["Qatar Airways","10:30 PM","8:15 PM","1 stop","$779",32],["Etihad","2:20 PM","1:35 PM","1 stop","$815",34]].map((flight,i)=><div key={flight[0]} className={`relative grid grid-cols-[1.2fr_1fr_auto] items-center gap-4 rounded-xl border bg-page-card p-4 ${i===0?"border-agent shadow-lg":"border-page-border"}`}><div><b className="text-sm text-page-strong">{flight[0]}</b><p className="text-xs text-page-muted">JFK → DXB</p></div><div><p className="text-sm text-page-strong">{flight[1]} — {flight[2]}</p><p className="text-xs text-page-muted">{flight[3]} · 12h 35m</p></div><b className="text-page-strong">{flight[4]}</b>{i===0&&<IndexBadge n={flight[5] as number}/>}</div>)}</div></div></div>;
}

function FoodPage() {
  return <div className="mock-page bg-page"><div className="mock-nav"><b className="text-page-strong">Local</b><div className="ml-auto flex w-72 items-center gap-2 rounded-full bg-page-soft px-4 py-2 text-page-muted"><Search className="size-4"/>Pizza near me</div></div><div className="mx-auto max-w-4xl p-7"><div className="rounded-2xl bg-food-banner p-7 text-food-foreground"><p className="text-sm opacity-75">Wood-fired since 1996</p><h2 className="mt-1 text-3xl font-bold">Piccolo Forno</h2><div className="mt-3 flex gap-4 text-sm"><span>★ 4.8</span><span>20–30 min</span><span>$0 delivery</span></div></div><h3 className="mt-7 text-lg font-semibold text-page-strong">Popular near you</h3><div className="mt-4 grid grid-cols-3 gap-4">{[["Margherita","Tomato, fior di latte, basil","$18",19],["Diavola","Spicy salami, mozzarella","$21",20],["Funghi","Mushrooms, thyme, pecorino","$20",21]].map((item,i)=><div key={item[0]} className={`relative overflow-hidden rounded-xl border bg-page-card ${i===0?"border-agent":"border-page-border"}`}><div className={`h-28 ${i===0?"bg-pizza-one":i===1?"bg-pizza-two":"bg-pizza-three"}`}><div className="pizza-disc"/></div><div className="p-3"><b className="text-page-strong">{item[0]}</b><p className="mt-1 h-8 text-xs text-page-muted">{item[1]}</p><p className="mt-3 font-semibold text-page-strong">{item[2]}</p></div>{i===0&&<IndexBadge n={item[3] as number}/>}</div>)}</div></div></div>;
}

function SearchPage() {
  return <div className="mock-page bg-page"><div className="mx-auto max-w-3xl px-8 pt-14"><div className="flex items-center gap-3"><div className="size-9 rounded-xl bg-search-mark"/><div className="relative flex-1 rounded-full border border-agent bg-page-card px-5 py-3 text-sm text-page-strong">best laptops under $1000 for work and travel <IndexBadge n={5}/></div></div><div className="mt-8 border-b border-page-border pb-3 text-sm text-page-muted">About 8,420 results</div><div className="space-y-7 py-6">{[["The best laptops under $1,000 in 2026","Independent benchmarks across battery, display and performance.","Tech Ledger"],["Top lightweight laptops for remote work","Our lab-tested shortlist focuses on endurance and portability.","Review Lab"],["Laptop deals and price history","Compare current prices across trusted retailers.","Market Watch"]].map((r,i)=><div key={r[0]} className="relative"><p className="text-xs text-page-muted">{r[2]}</p><h3 className="mt-1 text-lg font-medium text-page-link">{r[0]}</h3><p className="mt-1 text-sm leading-6 text-page-muted">{r[1]}</p>{i===0&&<IndexBadge n={11}/>}</div>)}</div></div></div>;
}

function ShoppingPage() {
  const items = [["Nova Air 14","4.8","18h","2.7 lb","$899"],["Framework 13","4.7","14h","2.9 lb","$949"],["Zenbook S","4.6","16h","2.6 lb","$999"]];
  return <div className="mock-page bg-page"><div className="mock-nav"><b className="text-page-strong">Compare</b><span className="ml-auto rounded-full bg-page-soft px-3 py-1 text-xs text-page-muted">Under $1,000</span></div><div className="p-7"><h2 className="text-2xl font-semibold text-page-strong">Three standouts</h2><p className="mt-1 text-sm text-page-muted">Balanced for performance, battery life, and portability.</p><div className="mt-6 grid grid-cols-3 gap-4">{items.map((item,i)=><div key={item[0]} className={`relative rounded-2xl border bg-page-card p-4 ${i===0?"border-agent shadow-lg":"border-page-border"}`}><div className={`laptop-art ${i===0?"bg-laptop-one":i===1?"bg-laptop-two":"bg-laptop-three"}`}><div/></div><div className="mt-4 flex items-start justify-between"><div><b className="text-page-strong">{item[0]}</b><p className="mt-1 flex items-center gap-1 text-xs text-page-muted"><Star className="size-3 fill-current"/>{item[1]}</p></div><b className="text-page-strong">{item[4]}</b></div><div className="mt-4 flex justify-between border-t border-page-border pt-3 text-xs text-page-muted"><span>{item[2]} battery</span><span>{item[3]}</span></div>{i===0&&<IndexBadge n={26}/>}</div>)}</div></div></div>;
}

function CheckoutPage({ scenario }: { scenario: ResultKind }) {
  const food = scenario === "food";
  return <div className="mock-page bg-page"><div className="mx-auto max-w-xl p-9"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-page-soft"><ShoppingBag className="size-5 text-page-strong"/></div><div><h2 className="font-semibold text-page-strong">Review {food?"your order":"booking"}</h2><p className="text-xs text-page-muted">Nothing happens without your approval</p></div></div><div className="mt-7 rounded-2xl border border-page-border bg-page-card p-5"><div className="flex justify-between"><div><b className="text-page-strong">{food?"Margherita pizza":"Emirates · Economy"}</b><p className="mt-1 text-sm text-page-muted">{food?"Piccolo Forno · 20–30 min":"JFK → DXB · Nonstop"}</p></div><b className="text-page-strong">{food?"$24.80":"$842.00"}</b></div><div className="mt-5 space-y-3 border-t border-page-border pt-4 text-sm text-page-muted"><div className="flex justify-between"><span>Payment</span><span>•••• 4242</span></div><div className="flex justify-between"><span>{food?"Delivery":"Passenger"}</span><span>Ready</span></div></div><div className="relative mt-5 flex h-11 items-center justify-center rounded-xl bg-page-action font-semibold text-page-action-foreground">Waiting for approval <IndexBadge n={food?29:31}/></div></div></div></div>;
}

function CompletePage() { return <div className="mock-page grid place-items-center bg-page"><div className="text-center"><div className="mx-auto grid size-16 place-items-center rounded-full bg-success-soft text-success"><Check className="size-7"/></div><h2 className="mt-5 text-2xl font-semibold text-page-strong">Task complete</h2><p className="mt-2 text-sm text-page-muted">Everything is ready. The details are in your conversation.</p></div></div>; }

export function MockPage({ page, scenario = "flight" }: { page: PageKind; scenario?: ResultKind }) {
  if (page === "food") return <FoodPage />;
  if (page === "search") return <SearchPage />;
  if (page === "shopping") return <ShoppingPage />;
  if (page === "checkout") return <CheckoutPage scenario={scenario}/>;
  if (page === "complete") return <CompletePage />;
  return <FlightsPage />;
}